### Full Config: https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/values.yaml

crds:
  keep: false # Remove CRDs on chart

global:
  image:
    tag: "v2.6.10"

configs:
  # General Argo CD configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    create: true # Create the argocd-cm configmap for [declarative setup]

    url: "${argocd_url}" # Argo CD's externally facing base URL (optional). Required when configuring SSO

    # Dex configuration
    dex.config:
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: "${github_client_id}"
            clientSecret: "${github_client_secret}"
            orgs:
              - name: "${github_org_name}"
        # - type: oidc
        #   id: google
        #   name: Google
        #   config:
        #       issuer: https://accounts.google.com
        #       clientID: "YOUR_CLIENT_ID"
        #       clientSecret: "YOUR_CLIENT_SECRET"

  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:
    ## Server properties
    server.insecure: true # Run server without TLS
